CREATE TABLE [dbo].[CODE_VALUE](
	[CODE_SERIAL_ID] [int] IDENTITY(1,1) NOT NULL,
	[CODE_ID] [int] NOT NULL,
	[CODE_VALUE] [varchar](100) NOT NULL,
	[CODE_VALUE_DESCRIPTION] [varchar](1000) NOT NULL,
	[DATA1] [varchar](500) NULL,
	[DATA2] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[CODE_SERIAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [dbo].[CODE_VALUE]  ADD FOREIGN KEY([CODE_ID])
REFERENCES [dbo].[Code_Id] ([Code_Id])
GO

