CREATE TABLE [dbo].[EXPENSES_TRACKER](
	[EXPENSES_TRACKER_ID] [int] IDENTITY(1,1) NOT NULL,
	[EXPENSES_ITEM] [varchar](500) NOT NULL,
	[EXPENSES_DATE] [varchar](500) NOT NULL,
	[EXPENSES_AMT] [int] NOT NULL,
	[EXPENSES_CATEGORY_ID] [int] NULL,
	[EXPENSES_TYPE_ID] INT NOT NULL,
	[EXPENSES_TYPE_VALUE] Varchar(100) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[EXPENSES_TRACKER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[EXPENSES_TRACKER]  ADD FOREIGN KEY([EXPENSES_CATEGORY_ID])
REFERENCES [dbo].[Expenses_Category] ([Expenses_Category_Id])
GO

